// Command repogen generates the `repositories:` manifest for repos.yaml from
// the GitHub API: every non-archived repository in an org with a push in the
// last N days (the brief's definition of "active"). Output goes to stdout so
// the operator reviews before committing:
//
//	GITHUB_TOKEN=<read-only PAT> go run ./cmd/repogen --org your-org > config/repos.yaml
//
// Names that fail the indexer's repo-name validation are skipped with a
// warning rather than emitted as config that LoadConfig would reject.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"regexp"
	"strconv"
	"time"

	"gopkg.in/yaml.v3"
)

// validRepoName mirrors internal/index/config.go - keep in sync.
var validRepoName = regexp.MustCompile(`^[A-Za-z0-9_][A-Za-z0-9._-]*$`)

type ghRepo struct {
	Name          string    `json:"name"`
	Archived      bool      `json:"archived"`
	PushedAt      time.Time `json:"pushed_at"`
	DefaultBranch string    `json:"default_branch"`
	CloneURL      string    `json:"clone_url"`
	SSHURL        string    `json:"ssh_url"`
}

type repoEntry struct {
	Name   string `yaml:"name"`
	URL    string `yaml:"url"`
	Branch string `yaml:"branch"`
}

type manifest struct {
	Repositories []repoEntry `yaml:"repositories"`
	Org          orgSection  `yaml:"org"`
}

type orgSection struct {
	Prefixes []string `yaml:"prefixes"`
}

func main() {
	org := flag.String("org", "", "GitHub organization (required)")
	days := flag.Int("days", 90, "consider a repo active if pushed within this many days")
	useSSH := flag.Bool("ssh", false, "emit git@ SSH URLs instead of https clone URLs")
	apiBase := flag.String("api", "https://api.github.com", "GitHub API base (override for GitHub Enterprise)")
	flag.Parse()

	if *org == "" {
		fmt.Fprintln(os.Stderr, "usage: repogen --org <org> [--days 90] [--ssh]")
		os.Exit(2)
	}
	token := os.Getenv("GITHUB_TOKEN")
	if token == "" {
		fmt.Fprintln(os.Stderr, "WARNING: GITHUB_TOKEN not set - only public repos will be listed")
	}

	repos, err := listOrgRepos(*apiBase, *org, token)
	if err != nil {
		fmt.Fprintf(os.Stderr, "repogen: %v\n", err)
		os.Exit(1)
	}

	cutoff := time.Now().AddDate(0, 0, -*days)
	m := manifest{Org: orgSection{Prefixes: []string{"github.com/" + *org + "/"}}}
	skipped := 0
	for _, r := range repos {
		if r.Archived || r.PushedAt.Before(cutoff) {
			continue
		}
		if !validRepoName.MatchString(r.Name) {
			fmt.Fprintf(os.Stderr, "WARNING: skipping %q - name fails indexer validation\n", r.Name)
			skipped++
			continue
		}
		u := r.CloneURL
		if *useSSH {
			u = r.SSHURL
		}
		m.Repositories = append(m.Repositories, repoEntry{Name: r.Name, URL: u, Branch: r.DefaultBranch})
	}

	if len(m.Repositories) == 0 {
		fmt.Fprintf(os.Stderr, "repogen: no active repositories found in %s (last %d days)\n", *org, *days)
		os.Exit(1)
	}

	fmt.Printf("# Generated by cmd/repogen on %s - %d active repos in %s (pushed within %dd), %d skipped.\n",
		time.Now().Format("2006-01-02"), len(m.Repositories), *org, *days, skipped)
	fmt.Println("# Review before committing; add git/graphify/extractors sections as needed.")
	enc := yaml.NewEncoder(os.Stdout)
	enc.SetIndent(2)
	if err := enc.Encode(m); err != nil {
		fmt.Fprintf(os.Stderr, "repogen: encode: %v\n", err)
		os.Exit(1)
	}
}

// listOrgRepos pages through GET /orgs/{org}/repos. 100 per page, following
// until a short page. Rate limits are generous enough (5000/h authenticated)
// that a simple sequential walk is fine even for very large orgs.
func listOrgRepos(apiBase, org, token string) ([]ghRepo, error) {
	client := &http.Client{Timeout: 30 * time.Second}
	var all []ghRepo
	for page := 1; ; page++ {
		u := fmt.Sprintf("%s/orgs/%s/repos?per_page=100&type=all&page=%s",
			apiBase, url.PathEscape(org), strconv.Itoa(page))
		req, err := http.NewRequest(http.MethodGet, u, nil)
		if err != nil {
			return nil, err
		}
		req.Header.Set("Accept", "application/vnd.github+json")
		if token != "" {
			req.Header.Set("Authorization", "Bearer "+token)
		}
		resp, err := client.Do(req)
		if err != nil {
			return nil, fmt.Errorf("page %d: %w", page, err)
		}
		body, err := io.ReadAll(io.LimitReader(resp.Body, 8<<20))
		resp.Body.Close()
		if err != nil {
			return nil, fmt.Errorf("page %d: read: %w", page, err)
		}
		if resp.StatusCode != http.StatusOK {
			return nil, fmt.Errorf("page %d: GitHub returned %d: %s", page, resp.StatusCode, truncate(string(body), 300))
		}
		var batch []ghRepo
		if err := json.Unmarshal(body, &batch); err != nil {
			return nil, fmt.Errorf("page %d: parse: %w", page, err)
		}
		all = append(all, batch...)
		if len(batch) < 100 {
			return all, nil
		}
	}
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}
